
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt"
    message: |
      The system is: Linux - 6.4.0-150600.23.30-default - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/bin/g++ 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      CMakeCCompilerId.c:2:3: error: #error "A C++ compiler has been selected for C."
       # error "A C++ compiler has been selected for C."
         ^~~~~
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/bin/g++ 
      Build flags: 
      Id flags: -c 
      
      The output was:
      1
      CMakeCCompilerId.c:2:3: error: #error "A C++ compiler has been selected for C."
       # error "A C++ compiler has been selected for C."
         ^~~~~
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/bin/g++ 
      Build flags: 
      Id flags: -Aa 
      
      The output was:
      1
      <command-line>:0:1: error: missing '(' after predicate
      CMakeCCompilerId.c:2:3: error: #error "A C++ compiler has been selected for C."
       # error "A C++ compiler has been selected for C."
         ^~~~~
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/bin/g++ 
      Build flags: 
      Id flags: -D__CLASSIC_C__ 
      
      The output was:
      1
      CMakeCCompilerId.c:2:3: error: #error "A C++ compiler has been selected for C."
       # error "A C++ compiler has been selected for C."
         ^~~~~
      CMakeCCompilerId.c:448:64: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
       char const* info_compiler = "INFO" ":" "compiler[" COMPILER_ID "]";
                                                                      ^~~
      CMakeCCompilerId.c:810:64: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
       char const* info_platform = "INFO" ":" "platform[" PLATFORM_ID "]";
                                                                      ^~~
      CMakeCCompilerId.c:811:60: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
       char const* info_arch = "INFO" ":" "arch[" ARCHITECTURE_ID "]";
                                                                  ^~~
      CMakeCCompilerId.c:833:44: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
         "INFO" ":" "standard_default[" C_VERSION "]";
                                                  ^~~
      CMakeCCompilerId.c:843:1: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
       "]";
       ^~~
      CMakeCCompilerId.c:851:10: error: cannot declare ‘::main’ to be a global variable
       int main(argc, argv) int argc; char *argv[];
                ^~~~
      CMakeCCompilerId.c:851:10: error: ‘argc’ was not declared in this scope
      CMakeCCompilerId.c:851:16: error: ‘argv’ was not declared in this scope
       int main(argc, argv) int argc; char *argv[];
                      ^~~~
      CMakeCCompilerId.c:851:20: error: expression list treated as compound expression in initializer [-fpermissive]
       int main(argc, argv) int argc; char *argv[];
                          ^
      CMakeCCompilerId.c:851:38: error: storage size of ‘argv’ isn’t known
       int main(argc, argv) int argc; char *argv[];
                                            ^~~~
      CMakeCCompilerId.c:855:1: error: expected unqualified-id before ‘{’ token
       {
       ^
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/bin/g++ 
      Build flags: 
      Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 
      
      The output was:
      1
      g++: warning: ‘-mcpu=’ is deprecated; use ‘-mtune=’ or ‘-march=’ instead
      g++: error: unrecognized command line option ‘--target=arm-arm-none-eabi’
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/bin/g++ 
      Build flags: 
      Id flags: -c;-I__does_not_exist__ 
      
      The output was:
      1
      CMakeCCompilerId.c:2:3: error: #error "A C++ compiler has been selected for C."
       # error "A C++ compiler has been selected for C."
         ^~~~~
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/bin/g++ 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      CMakeCCompilerId.c:2:3: error: #error "A C++ compiler has been selected for C."
       # error "A C++ compiler has been selected for C."
         ^~~~~
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/bin/g++ 
      Build flags: 
      Id flags: -c 
      
      The output was:
      1
      CMakeCCompilerId.c:2:3: error: #error "A C++ compiler has been selected for C."
       # error "A C++ compiler has been selected for C."
         ^~~~~
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/bin/g++ 
      Build flags: 
      Id flags: -Aa 
      
      The output was:
      1
      <command-line>:0:1: error: missing '(' after predicate
      CMakeCCompilerId.c:2:3: error: #error "A C++ compiler has been selected for C."
       # error "A C++ compiler has been selected for C."
         ^~~~~
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/bin/g++ 
      Build flags: 
      Id flags: -D__CLASSIC_C__ 
      
      The output was:
      1
      CMakeCCompilerId.c:2:3: error: #error "A C++ compiler has been selected for C."
       # error "A C++ compiler has been selected for C."
         ^~~~~
      CMakeCCompilerId.c:448:64: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
       char const* info_compiler = "INFO" ":" "compiler[" COMPILER_ID "]";
                                                                      ^~~
      CMakeCCompilerId.c:810:64: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
       char const* info_platform = "INFO" ":" "platform[" PLATFORM_ID "]";
                                                                      ^~~
      CMakeCCompilerId.c:811:60: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
       char const* info_arch = "INFO" ":" "arch[" ARCHITECTURE_ID "]";
                                                                  ^~~
      CMakeCCompilerId.c:833:44: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
         "INFO" ":" "standard_default[" C_VERSION "]";
                                                  ^~~
      CMakeCCompilerId.c:843:1: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
       "]";
       ^~~
      CMakeCCompilerId.c:851:10: error: cannot declare ‘::main’ to be a global variable
       int main(argc, argv) int argc; char *argv[];
                ^~~~
      CMakeCCompilerId.c:851:10: error: ‘argc’ was not declared in this scope
      CMakeCCompilerId.c:851:16: error: ‘argv’ was not declared in this scope
       int main(argc, argv) int argc; char *argv[];
                      ^~~~
      CMakeCCompilerId.c:851:20: error: expression list treated as compound expression in initializer [-fpermissive]
       int main(argc, argv) int argc; char *argv[];
                          ^
      CMakeCCompilerId.c:851:38: error: storage size of ‘argv’ isn’t known
       int main(argc, argv) int argc; char *argv[];
                                            ^~~~
      CMakeCCompilerId.c:855:1: error: expected unqualified-id before ‘{’ token
       {
       ^
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/bin/g++ 
      Build flags: 
      Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 
      
      The output was:
      1
      g++: warning: ‘-mcpu=’ is deprecated; use ‘-mtune=’ or ‘-march=’ instead
      g++: error: unrecognized command line option ‘--target=arm-arm-none-eabi’
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/bin/g++ 
      Build flags: 
      Id flags: -c;-I__does_not_exist__ 
      
      The output was:
      1
      CMakeCCompilerId.c:2:3: error: #error "A C++ compiler has been selected for C."
       # error "A C++ compiler has been selected for C."
         ^~~~~
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:1144 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:86 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/usr/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
      g++: fatal error: no input files
      compilation terminated.
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:1144 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:86 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/usr/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
      g++: fatal error: no input files
      compilation terminated.
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /usr/bin/g++ 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"
      
      The CXX compiler identification is GNU, found in:
        /home/anvi_d/project/git_test/CMakeFiles/3.28.3/CompilerIdCXX/a.out
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/usr/share/cmake/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/home/anvi_d/project/git_test/CMakeFiles/CMakeScratch/TryCompile-ot7aO8"
      binary: "/home/anvi_d/project/git_test/CMakeFiles/CMakeScratch/TryCompile-ot7aO8"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/home/anvi_d/project/git_test/CMakeFiles/CMakeScratch/TryCompile-ot7aO8'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_58543/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_58543.dir/build.make CMakeFiles/cmTC_58543.dir/build
        gmake[1]: Entering directory '/home/anvi_d/project/git_test/CMakeFiles/CMakeScratch/TryCompile-ot7aO8'
        Building C object CMakeFiles/cmTC_58543.dir/CMakeCCompilerABI.c.o
        /usr/bin/g++    -o CMakeFiles/cmTC_58543.dir/CMakeCCompilerABI.c.o -c /usr/share/cmake/Modules/CMakeCCompilerABI.c
        /usr/share/cmake/Modules/CMakeCCompilerABI.c:2:4: error: #error "A C++ compiler has been selected for C."
         #  error "A C++ compiler has been selected for C."
            ^~~~~
        gmake[1]: *** [CMakeFiles/cmTC_58543.dir/build.make:78: CMakeFiles/cmTC_58543.dir/CMakeCCompilerABI.c.o] Error 1
        gmake[1]: Leaving directory '/home/anvi_d/project/git_test/CMakeFiles/CMakeScratch/TryCompile-ot7aO8'
        gmake: *** [Makefile:127: cmTC_58543/fast] Error 2
        
      exitCode: 2
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt"
    checks:
      - "Check for working C compiler: /usr/bin/g++"
    directories:
      source: "/home/anvi_d/project/git_test/CMakeFiles/CMakeScratch/TryCompile-jdyUhn"
      binary: "/home/anvi_d/project/git_test/CMakeFiles/CMakeScratch/TryCompile-jdyUhn"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: '/home/anvi_d/project/git_test/CMakeFiles/CMakeScratch/TryCompile-jdyUhn'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_89c42/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_89c42.dir/build.make CMakeFiles/cmTC_89c42.dir/build
        gmake[1]: Entering directory '/home/anvi_d/project/git_test/CMakeFiles/CMakeScratch/TryCompile-jdyUhn'
        Building C object CMakeFiles/cmTC_89c42.dir/testCCompiler.c.o
        /usr/bin/g++    -o CMakeFiles/cmTC_89c42.dir/testCCompiler.c.o -c /home/anvi_d/project/git_test/CMakeFiles/CMakeScratch/TryCompile-jdyUhn/testCCompiler.c
        /home/anvi_d/project/git_test/CMakeFiles/CMakeScratch/TryCompile-jdyUhn/testCCompiler.c:2:3: error: #error "The CMAKE_C_COMPILER is set to a C++ compiler"
         # error "The CMAKE_C_COMPILER is set to a C++ compiler"
           ^~~~~
        gmake[1]: *** [CMakeFiles/cmTC_89c42.dir/build.make:78: CMakeFiles/cmTC_89c42.dir/testCCompiler.c.o] Error 1
        gmake[1]: Leaving directory '/home/anvi_d/project/git_test/CMakeFiles/CMakeScratch/TryCompile-jdyUhn'
        gmake: *** [Makefile:127: cmTC_89c42/fast] Error 2
        
      exitCode: 2
...
